# Generated by Django 4.1.7 on 2025-09-11 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroTreinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('endereco', models.CharField(max_length=255)),
                ('contato', models.CharField(max_length=100)),
                ('modalidades', models.TextField(help_text='Modalidades oferecidas (texto livre)')),
            ],
            options={
                'verbose_name': 'Centro de Treinamento',
                'verbose_name_plural': 'Centros de Treinamento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor'), ('GERENTE', 'Gerente')], default='ALUNO', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('vagas', models.PositiveIntegerField()),
                ('nivel', models.CharField(max_length=50)),
                ('observacoes', models.TextField(blank=True)),
                ('ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinos', to='main.centrotreinamento')),
                ('professor', models.ForeignKey(limit_choices_to={'usuario__tipo': 'PROFESSOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='treinos_ministrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(limit_choices_to={'usuario__tipo': 'ALUNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to=settings.AUTH_USER_MODEL)),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='main.treino')),
            ],
            options={
                'ordering': ['-criado_em'],
                'unique_together': {('treino', 'aluno')},
            },
        ),
    ]
