# Generated by Django 4.1.7 on 2025-09-25 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="centrotreinamento",
            name="gerente",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuário gerente responsável pelo CT",
                limit_choices_to={"usuario__tipo": "GERENTE"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cts_gerenciados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
