# Generated by Django 4.1.7 on 2025-09-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_centrotreinamento_gerente"),
    ]

    operations = [
        migrations.AddField(
            model_name="centrotreinamento",
            name="cnpj",
            field=models.CharField(
                default="00.000.000/0000-00",
                help_text="CNPJ do CT (com ou sem máscara)",
                max_length=18,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
