# Generated by Django 4.1.7 on 2025-09-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_centrotreinamento_cnpj"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="certificacoes",
            field=models.TextField(
                blank=True, help_text="Certificações (uma por linha ou texto livre)"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="nivel",
            field=models.CharField(
                blank=True,
                help_text="Ex.: Iniciante, Intermediário, Avançado",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="telefone",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
