# Generated by Django 4.1.7 on 2025-09-30 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_usuario_certificacoes_usuario_nivel_usuario_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrotreinamento',
            name='professores',
            field=models.ManyToManyField(blank=True, help_text='Professores autorizados a ministrar treinos neste CT', limit_choices_to={'usuario__tipo': 'PROFESSOR'}, related_name='cts_associados', to=settings.AUTH_USER_MODEL),
        ),
    ]
