# Generated by Django 4.1.7 on 2025-11-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_inscricao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrotreinamento',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude da localização do CT (ex: -22.9068)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='centrotreinamento',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude da localização do CT (ex: -43.1729)', max_digits=9, null=True),
        ),
    ]
