# Generated by Django 4.1.7 on 2025-12-03 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_centrotreinamento_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(max_length=100)),
                ('vagas', models.PositiveIntegerField()),
                ('nivel', models.CharField(max_length=50)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='main.centrotreinamento')),
                ('professor', models.ForeignKey(limit_choices_to={'usuario__tipo': 'PROFESSOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_treino', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HorarioRecorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='main.agendamentotreino')),
            ],
            options={'ordering': ['dia_semana', 'hora_inicio']},
        ),
        migrations.AddField(
            model_name='treino',
            name='agendado',
            field=models.BooleanField(default=False, help_text='Identifica treinos gerados a partir de um agendamento.'),
        ),
        migrations.AddField(
            model_name='treino',
            name='agendamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='main.agendamentotreino'),
        ),
        migrations.AlterUniqueTogether(
            name='horariorecorrente',
            unique_together={('agendamento', 'dia_semana', 'hora_inicio', 'hora_fim')},
        ),
    ]
