# Generated by Django 4.1.7 on 2025-12-16
from django.conf import settings
from django.db import migrations, models


def copy_existing_professores(apps, schema_editor):
    ProfessorCentroTreinamento = apps.get_model("main", "ProfessorCentroTreinamento")
    table_name = "main_centrotreinamento_professores"
    connection = schema_editor.connection
    if table_name not in connection.introspection.table_names():
        return

    with connection.cursor() as cursor:
        cursor.execute(f"SELECT centrotreinamento_id, user_id FROM {table_name}")
        rows = cursor.fetchall()

    for ct_id, professor_id in rows:
        # Keep existing vinculos; flags default to False
        ProfessorCentroTreinamento.objects.get_or_create(
            ct_id=ct_id,
            professor_id=professor_id,
            defaults={"pode_criar_treino": False, "pode_cancelar_treino": False},
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0008_agendamentorecorrente_horariorecorrente_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfessorCentroTreinamento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pode_criar_treino", models.BooleanField(default=False)),
                ("pode_cancelar_treino", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "ct",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="professores_vinculos",
                        to="main.centrotreinamento",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        limit_choices_to={"usuario__tipo": "PROFESSOR"},
                        on_delete=models.CASCADE,
                        related_name="vinculos_ct",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Professor no CT",
                "verbose_name_plural": "Professores no CT",
                "unique_together": {("ct", "professor")},
            },
        ),
        migrations.RunPython(copy_existing_professores, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="centrotreinamento",
            name="professores",
        ),
        migrations.AddField(
            model_name="centrotreinamento",
            name="professores",
            field=models.ManyToManyField(
                blank=True,
                help_text="Professores autorizados a ministrar treinos neste CT",
                limit_choices_to={"usuario__tipo": "PROFESSOR"},
                related_name="cts_associados",
                through="main.ProfessorCentroTreinamento",
                through_fields=("ct", "professor"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
